name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Replace environment variables
        run: |
          sed -i "s|process.env.FIREBASE_API_KEY|'${{ secrets.FIREBASE_API_KEY }}'|g" uno/js/firebase.js
          sed -i "s|process.env.FIREBASE_AUTH_DOMAIN|'${{ secrets.FIREBASE_AUTH_DOMAIN }}'|g" uno/js/firebase.js
          sed -i "s|process.env.FIREBASE_DATABASE_URL|'${{ secrets.FIREBASE_DATABASE_URL }}'|g" uno/js/firebase.js
          sed -i "s|process.env.FIREBASE_PROJECT_ID|'${{ secrets.FIREBASE_PROJECT_ID }}'|g" uno/js/firebase.js
          sed -i "s|process.env.FIREBASE_STORAGE_BUCKET|'${{ secrets.FIREBASE_STORAGE_BUCKET }}'|g" uno/js/firebase.js
          sed -i "s|process.env.FIREBASE_MESSAGING_SENDER_ID|'${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'|g" uno/js/firebase.js
          sed -i "s|process.env.FIREBASE_APP_ID|'${{ secrets.FIREBASE_APP_ID }}'|g" uno/js/firebase.js
          sed -i "s|process.env.FIREBASE_MEASUREMENT_ID|'${{ secrets.FIREBASE_MEASUREMENT_ID }}'|g" uno/js/firebase.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ 
          publish_branch: main
          force_orphan: true