name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Stap 1: Haal de code op
      - name: Checkout code
        uses: actions/checkout@v3

      # Stap 2: Installeer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Stap 3: Vervang placeholders in firebase.js door GitHub Secrets
      - name: Replace environment variables
        run: |
          sed -i "s|{{FIREBASE_API_KEY}}|${{ secrets.FIREBASE_API_KEY }}|g" uno/js/firebase.js
          sed -i "s|{{FIREBASE_AUTH_DOMAIN}}|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" uno/js/firebase.js
          sed -i "s|{{FIREBASE_DATABASE_URL}}|${{ secrets.FIREBASE_DATABASE_URL }}|g" uno/js/firebase.js
          sed -i "s|{{FIREBASE_PROJECT_ID}}|${{ secrets.FIREBASE_PROJECT_ID }}|g" uno/js/firebase.js
          sed -i "s|{{FIREBASE_STORAGE_BUCKET}}|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" uno/js/firebase.js
          sed -i "s|{{FIREBASE_MESSAGING_SENDER_ID}}|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" uno/js/firebase.js
          sed -i "s|{{FIREBASE_APP_ID}}|${{ secrets.FIREBASE_APP_ID }}|g" uno/js/firebase.js
          sed -i "s|{{FIREBASE_MEASUREMENT_ID}}|${{ secrets.FIREBASE_MEASUREMENT_ID }}|g" uno/js/firebase.js

      # Stap 4: Deploy naar GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true